mkdir -p .github/workflows 
cat > .github/workflows/ci.yml <<'YML'
name: CI - Train Models

on:
  push:
    branches:
      - kernelridge
      - dtree
      - main

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Decision Tree training (train.py)
        run: |
          python train.py

      - name: Run KernelRidge training (train2.py)
        run: |
          python train2.py --kernel linear --alpha 1.0
YML
